#!/bin/bash
# Task: Continuous Online test-time adaptation
# Dataset: CIFAR10-C, ImageNet-C
# Model: WRN-40-2, ResNet-18

# CIFAR10-C with WRN-40-2
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16341 online.py --dataset cifar10-c --dataset_path ./data/ --corruption gaussian_noise --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/gaussian_noise/5/
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16342 online.py --dataset cifar10-c --dataset_path ./data/ --corruption shot_noise --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/shot_noise/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/gaussian_noise/5/WRN-40-2_cifar10-c_gaussian_noise_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16343 online.py --dataset cifar10-c --dataset_path ./data/ --corruption impulse_noise --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/impulse_noise/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/shot_noise/5/WRN-40-2_cifar10-c_shot_noise_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16344 online.py --dataset cifar10-c --dataset_path ./data/ --corruption defocus_blur --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/defocus_blur/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/impulse_noise/5/WRN-40-2_cifar10-c_impulse_noise_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16345 online.py --dataset cifar10-c --dataset_path ./data/ --corruption glass_blur --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/glass_blur/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/defocus_blur/5/WRN-40-2_cifar10-c_defocus_blur_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16346 online.py --dataset cifar10-c --dataset_path ./data/ --corruption motion_blur --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/motion_blur/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/glass_blur/5/WRN-40-2_cifar10-c_glass_blur_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16347 online.py --dataset cifar10-c --dataset_path ./data/ --corruption zoom_blur --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/zoom_blur/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/motion_blur/5/WRN-40-2_cifar10-c_motion_blur_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16348 online.py --dataset cifar10-c --dataset_path ./data/ --corruption snow --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/snow/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/zoom_blur/5/WRN-40-2_cifar10-c_zoom_blur_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16349 online.py --dataset cifar10-c --dataset_path ./data/ --corruption frost --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/frost/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/snow/5/WRN-40-2_cifar10-c_snow_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16350 online.py --dataset cifar10-c --dataset_path ./data/ --corruption fog --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/fog/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/frost/5/WRN-40-2_cifar10-c_frost_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16351 online.py --dataset cifar10-c --dataset_path ./data/ --corruption brightness --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/brightness/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/fog/5/WRN-40-2_cifar10-c_fog_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16352 online.py --dataset cifar10-c --dataset_path ./data/ --corruption contrast --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/contrast/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/brightness/5/WRN-40-2_cifar10-c_brightness_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16353 online.py --dataset cifar10-c --dataset_path ./data/ --corruption elastic_transform --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/elastic_transform/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/contrast/5/WRN-40-2_cifar10-c_contrast_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16354 online.py --dataset cifar10-c --dataset_path ./data/ --corruption pixelate --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/pixelate/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/elastic_transform/5/WRN-40-2_cifar10-c_elastic_transform_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16355 online.py --dataset cifar10-c --dataset_path ./data/ --corruption jpeg_compression --level 5 --model WRN-40-2 --pretrained --num_classes 10 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/cifar10-c_WRN-40-2/jpeg_compression/5/ --model_load_path ./results/continuous_online/cifar10-c_WRN-40-2/pixelate/5/WRN-40-2_cifar10-c_pixelate_5_adapt.pth

# ImageNet-C with ResNet18
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16356 online.py --dataset imagenet-c --dataset_path ./data/ --corruption gaussian_noise --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/gaussian_noise/5/
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16357 online.py --dataset imagenet-c --dataset_path ./data/ --corruption shot_noise --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/shot_noise/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/gaussian_noise/5/resnet18_fc_imagenet-c_gaussian_noise_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16358 online.py --dataset imagenet-c --dataset_path ./data/ --corruption impulse_noise --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/impulse_noise/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/shot_noise/5/resnet18_fc_imagenet-c_shot_noise_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16359 online.py --dataset imagenet-c --dataset_path ./data/ --corruption defocus_blur --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/defocus_blur/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/impulse_noise/5/resnet18_fc_imagenet-c_impulse_noise_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16360 online.py --dataset imagenet-c --dataset_path ./data/ --corruption glass_blur --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/glass_blur/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/defocus_blur/5/resnet18_fc_imagenet-c_defocus_blur_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16361 online.py --dataset imagenet-c --dataset_path ./data/ --corruption motion_blur --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/motion_blur/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/glass_blur/5/resnet18_fc_imagenet-c_glass_blur_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16362 online.py --dataset imagenet-c --dataset_path ./data/ --corruption zoom_blur --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/zoom_blur/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/motion_blur/5/resnet18_fc_imagenet-c_motion_blur_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16363 online.py --dataset imagenet-c --dataset_path ./data/ --corruption snow --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/snow/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/zoom_blur/5/resnet18_fc_imagenet-c_zoom_blur_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16364 online.py --dataset imagenet-c --dataset_path ./data/ --corruption frost --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/frost/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/snow/5/resnet18_fc_imagenet-c_snow_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16365 online.py --dataset imagenet-c --dataset_path ./data/ --corruption fog --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/fog/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/frost/5/resnet18_fc_imagenet-c_frost_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16366 online.py --dataset imagenet-c --dataset_path ./data/ --corruption brightness --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/brightness/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/fog/5/resnet18_fc_imagenet-c_fog_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16367 online.py --dataset imagenet-c --dataset_path ./data/ --corruption contrast --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/contrast/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/brightness/5/resnet18_fc_imagenet-c_brightness_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16368 online.py --dataset imagenet-c --dataset_path ./data/ --corruption elastic_transform --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/elastic_transform/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/contrast/5/resnet18_fc_imagenet-c_contrast_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16369 online.py --dataset imagenet-c --dataset_path ./data/ --corruption pixelate --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/pixelate/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/elastic_transform/5/resnet18_fc_imagenet-c_elastic_transform_5_adapt.pth
python -m torch.distributed.launch --nproc_per_node 1 --master_port 16370 online.py --dataset imagenet-c --dataset_path ./data/ --corruption jpeg_compression --level 5 --model resnet18_fc --pretrained --num_classes 1000 --iters 1 --batch_size 128 --save_model --save_path ./results/continuous_online/imagenet-c_resnet18/jpeg_compression/5/ --model_load_path ./results/continuous_online/imagenet-c_resnet18/pixelate/5/resnet18_fc_imagenet-c_pixelate_5_adapt.pth
